sudo: false
language: python
dist: xenial # default is ubuntu 14.04, we need at least 16.04
python: # test various python versions
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1
  - DJANGO=master
matrix:
  exclude:
    # Django >= 3.0 does not support Python3.5 anymore
    - { python: "3.5", env: DJANGO=3.0 }
    - { python: "3.5", env: DJANGO=3.1 }
    - { python: "3.5", env: DJANGO=master }
  allow_failures:
    # newer python versions aswell as pypy may also always break our build
    - python: "pypy3"
    - env: DJANGO=master
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox-travis
script: tox
